"""inicial migração 03 

Revision ID: 55885d758ff6
Revises: 
Create Date: 2026-03-01 17:22:38.556510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55885d758ff6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idade', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('nacao', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('altura', sa.Float(precision=10, asdecimal=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogadores', schema=None) as batch_op:
        batch_op.drop_column('altura')
        batch_op.drop_column('nacao')
        batch_op.drop_column('idade')

    # ### end Alembic commands ###
