"""inicial migração 06 

Revision ID: 688d06dafdbb
Revises: 55885d758ff6
Create Date: 2026-03-01 18:23:54.492163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688d06dafdbb'
down_revision = '55885d758ff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posicao1', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('posicao2', sa.String(length=10), nullable=True))
        batch_op.alter_column('altura',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogadores', schema=None) as batch_op:
        batch_op.alter_column('altura',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.drop_column('posicao2')
        batch_op.drop_column('posicao1')

    # ### end Alembic commands ###
