"""inicial migração 07 

Revision ID: 84c0c34dc57d
Revises: 688d06dafdbb
Create Date: 2026-03-01 19:48:37.858199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c0c34dc57d'
down_revision = '688d06dafdbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lado_dominate', sa.String(length=50), nullable=True))
        batch_op.alter_column('altura',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10, asdecimal=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogadores', schema=None) as batch_op:
        batch_op.alter_column('altura',
               existing_type=sa.Float(precision=10, asdecimal=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.drop_column('lado_dominate')

    # ### end Alembic commands ###
